"""visualize.py — Stage 3: turn a run's results.json into heatmaps and a table.

Only results.json is read, so the figures can be restyled without recomputing anything. Every
number is a mean +- std over the repeat seeds, in percent. Where a cell was run at several
anchor budgets, the table and the top-level heatmaps show the budget with the best mean
full accuracy.

Written next to results.json, in output/<run_id>/<process>/<variant>/T<T_true>/:
    table.tex, table.png       full accuracy of every predictor on the (d, K) grid
    <model>.png                full accuracy / mode F1 / hallucination F1 heatmaps
    anchors_<b>/<model>.png    the same heatmaps at one anchor budget b
"""
from __future__ import annotations
import json
import os
import traceback

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from train import resolve_sweep_dir, variant_of

PANELS = [("full_acc", "full accuracy"), ("mode_f1", "mode F1"), ("hall_f1", "hallucination F1")]
NAN = float("nan")


def best_rows(rows, model):
    """For one model, the row with the best mean full accuracy in each (d, K) cell."""
    best = {}
    for r in rows:
        key = (r["d"], r["K"])
        if r["model"] == model and (key not in best or r["full_acc"] > best[key]["full_acc"]):
            best[key] = r
    return best


def plot_model(cells, ds, Ks, model, title, out_dir):
    """One row of heatmaps (d across, K down), coloured by the mean, labelled 'mean+-std'."""
    fig, axes = plt.subplots(1, len(PANELS), figsize=(4.2 * len(PANELS), 0.55 * len(Ks) + 3.0), squeeze=False)
    for ax, (key, label) in zip(axes[0], PANELS):
        mean = np.array([[cells[(d, K)][key] if (d, K) in cells else NAN for d in ds] for K in Ks])
        std = np.array([[cells[(d, K)].get(key + "_std", NAN) if (d, K) in cells else NAN for d in ds] for K in Ks])
        im = ax.imshow(mean, vmin=0, vmax=1, aspect="auto", cmap="viridis")
        ax.set_xticks(range(len(ds))); ax.set_xticklabels(ds)
        ax.set_yticks(range(len(Ks))); ax.set_yticklabels(Ks)
        ax.set_xlabel("dimension $d$"); ax.set_ylabel("modes $K$")
        ax.set_title(label, fontsize=10)
        for i in range(len(Ks)):
            for j in range(len(ds)):
                v, sd = mean[i, j], std[i, j]
                if v == v:                                       # skip empty cells (NaN)
                    txt = f"{v * 100:.0f}" if sd != sd else f"{v * 100:.0f}$\\pm${sd * 100:.0f}"
                    ax.text(j, i, txt, ha="center", va="center", fontsize=7,
                            color="white" if v < 0.6 else "black")
    fig.colorbar(im, ax=axes[0].tolist(), fraction=0.025, pad=0.02)
    fig.suptitle(title, fontsize=12)
    path = os.path.join(out_dir, f"{model}.png")
    fig.savefig(path, dpi=150, bbox_inches="tight"); plt.close(fig)
    return path


def table_rows(rows, ds, Ks, models):
    """[(K, d, [(mean, std) of full accuracy per model])], at each model's best budget."""
    out = []
    for K in Ks:
        for d in ds:
            vals = []
            for m in models:
                r = best_rows(rows, m).get((d, K))
                vals.append((r["full_acc"], r.get("full_acc_std", NAN)) if r else (NAN, NAN))
            out.append((K, d, vals))
    return out


def write_tex(rows, ds, Ks, models, name, T_true, n_seeds, out_dir):
    lines = ["% Auto-generated by visualize.py -- requires \\usepackage{booktabs}",
             "\\begin{table}[t]", "\\centering",
             f"\\caption{{Seed-fate full accuracy (\\%, mean $\\pm$ std over {n_seeds} seeds) on the "
             f"$(d,K)$ grid ({name}, $T={T_true}$), best anchor budget per cell.}}",
             f"\\label{{tab:atlas-{name}}}",
             f"\\begin{{tabular}}{{{'cc ' + 'r' * len(models)}}}", "\\toprule",
             "$K$ & $d$ & " + " & ".join(models) + " \\\\", "\\midrule"]
    prev_K = None
    for K, d, vals in table_rows(rows, ds, Ks, models):
        if prev_K is not None and K != prev_K:
            lines.append("\\midrule")                            # a rule between K blocks
        prev_K = K
        cells = " & ".join("--" if mu != mu else f"{mu * 100:.1f} $\\pm$ {sd * 100:.1f}" for mu, sd in vals)
        lines.append(f"{K} & {d} & {cells} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    path = os.path.join(out_dir, "table.tex")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path


def write_png(rows, ds, Ks, models, name, T_true, n_seeds, out_dir):
    fmt = lambda mu, sd: "--" if mu != mu else f"{mu * 100:.1f}$\\pm${sd * 100:.1f}"
    header = ["$K$", "$d$"] + models
    cells = [[str(K), str(d)] + [fmt(mu, sd) for mu, sd in vals]
             for K, d, vals in table_rows(rows, ds, Ks, models)]
    fig, ax = plt.subplots(figsize=(1.6 * len(header) + 1.5, 0.34 * len(cells) + 1.8))
    ax.axis("off")
    tb = ax.table(cellText=cells, colLabels=header, loc="center", cellLoc="center")
    tb.auto_set_font_size(False); tb.set_fontsize(8); tb.scale(1, 1.35)
    for (row, _), cell in tb.get_celld().items():               # bold header, striped rows
        cell.set_linewidth(0.4)
        if row == 0:
            cell.set_text_props(weight="bold"); cell.set_facecolor("#e8e8e8")
        elif row % 2 == 0:
            cell.set_facecolor("#f6f6f6")
    ax.set_title(f"{name}  |  T = {T_true}  |  full accuracy % (mean $\\pm$ std, {n_seeds} seeds), "
                 f"best budget", fontsize=10, pad=12)
    path = os.path.join(out_dir, "table.png")
    fig.savefig(path, dpi=200, bbox_inches="tight"); plt.close(fig)
    return path


def run(cfg):
    out_dir = resolve_sweep_dir(cfg.paths.output, cfg.run_id, cfg.process.name, cfg.process.T_true, variant_of(cfg))
    if out_dir is None:
        raise FileNotFoundError(f"no results for {cfg.process.name}/{variant_of(cfg)} T={cfg.process.T_true} "
                                f"under {cfg.paths.output}/{cfg.run_id}")
    with open(os.path.join(out_dir, "results.json")) as f:
        blob = json.load(f)
    rows = blob["aggregate"]
    if not rows:
        print("[viz] results.json is empty, nothing to plot")
        return

    name = f"{blob['sampler']}/{blob['variant']}"               # e.g. ddim/weighted, in every title
    T_true = blob["config_sweep"]["T_true"]
    ds, Ks = sorted({r["d"] for r in rows}), sorted({r["K"] for r in rows})
    models = list(dict.fromkeys(r["model"] for r in rows))      # in order of appearance
    n_seeds = max(int(r["n_seeds"]) for r in rows)

    made = []

    def attempt(fn, *args):
        """A failing figure is reported but does not stop the others."""
        try:
            made.append(fn(*args))
        except Exception:
            print(f"[viz] {fn.__name__} failed:")
            traceback.print_exc()

    attempt(write_tex, rows, ds, Ks, models, name, T_true, n_seeds, out_dir)
    attempt(write_png, rows, ds, Ks, models, name, T_true, n_seeds, out_dir)
    for m in models:
        attempt(plot_model, best_rows(rows, m), ds, Ks, m,
                f"{m} (% correct, mean$\\pm$std over {n_seeds} seeds, best anchor budget)", out_dir)
    for b in sorted({int(r["n_per_mode"]) for r in rows}):
        b_dir = os.path.join(out_dir, f"anchors_{b}")
        os.makedirs(b_dir, exist_ok=True)
        rows_b = [r for r in rows if int(r["n_per_mode"]) == b]
        for m in models:
            attempt(plot_model, best_rows(rows_b, m), ds, Ks, m,
                    f"{m} (% correct, mean$\\pm$std over {n_seeds} seeds, {b} anchors/mode)", b_dir)
    for p in made:
        print(f"[viz] wrote {p}")
