"""
visualize.py — Stage 3. Turn output/results.json into figures under cfg.paths.viz.

Reads only the results file (never re-runs the models), so plotting is cheap and can be
re-styled independently of the sweep. Produces:
  - accuracy_vs_dimension.png : class accuracy vs d, per method, faceted by K
  - accuracy_vs_anchors.png   : atlas class accuracy vs anchor count, per (d,K)
  - hallucination_vs_dim.png  : ground-truth hallucination rate vs d
"""
from __future__ import annotations
import os
import json
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


def _load(cfg):
    js = os.path.join(cfg.paths.output, cfg.sampler, "results.json")
    with open(js) as f:
        return json.load(f)


def _by_dk(results):
    return {(r["d"], r["K"]): r for r in results}


def plot_accuracy_vs_dimension(cfg, blob, viz_dir):
    results = blob["results"]
    Ks = sorted({r["K"] for r in results})
    ds = sorted({r["d"] for r in results})
    dk = _by_dk(results)
    n = len(Ks)
    fig, axes = plt.subplots(1, n, figsize=(5 * n, 4.5), squeeze=False)
    for ax, K in zip(axes[0], Ks):
        xs = [d for d in ds if (d, K) in dk]
        resp = [dk[(d, K)]["responsibility"]["class_acc"] for d in xs]
        atlas_best = [max((a["class_acc"] for a in dk[(d, K)]["atlas"]), default=float("nan"))
                      for d in xs]
        ax.plot(xs, resp, "o-", label="responsibility (no anchors)")
        ax.plot(xs, atlas_best, "s-", label="atlas (best anchors)")
        ax.axhline(0.9, color="gray", ls=":", alpha=.7)
        ax.set_xscale("log", base=2)
        ax.set_xticks(xs); ax.set_xticklabels(xs)
        ax.set_ylim(0, 1.02); ax.grid(alpha=.3)
        ax.set_xlabel("dimension d"); ax.set_ylabel("class accuracy")
        ax.set_title(f"K = {K}"); ax.legend(fontsize=8)
    fig.suptitle("Class accuracy vs dimension", fontsize=13)
    fig.tight_layout()
    p = os.path.join(viz_dir, "accuracy_vs_dimension.png")
    fig.savefig(p, dpi=150, bbox_inches="tight"); plt.close(fig)
    return p


def plot_accuracy_vs_anchors(cfg, blob, viz_dir):
    results = blob["results"]
    fig, ax = plt.subplots(figsize=(8, 5))
    for r in results:
        xs = [a["n_anchors"] for a in r["atlas"]]
        ys = [a["class_acc"] for a in r["atlas"]]
        if xs:
            ax.plot(xs, ys, "o-", label=f"d={r['d']}, K={r['K']}")
    ax.set_xscale("log"); ax.set_ylim(0, 1.02); ax.grid(alpha=.3)
    ax.set_xlabel("number of anchors"); ax.set_ylabel("atlas class accuracy")
    ax.set_title("Atlas accuracy vs anchor budget")
    ax.legend(fontsize=7, ncol=2)
    fig.tight_layout()
    p = os.path.join(viz_dir, "accuracy_vs_anchors.png")
    fig.savefig(p, dpi=150, bbox_inches="tight"); plt.close(fig)
    return p


def write_latex_table(cfg, blob, viz_dir):
    """
    Publication-ready LaTeX table (booktabs). One row per (K, d):
      K | d | Best acc | Anchors@best | Mode acc | Halluc. acc
    - Best acc  = best FULL accuracy across anchor counts (exact-label match).
    - Anchors   = the anchor count achieving that best.
    - Mode/Hall = per-class accuracy AT that same best anchor count; any mislabel is wrong.
    """
    sampler = blob.get("sampler", cfg.sampler)
    results = sorted(blob["results"], key=lambda r: (r["K"], r["d"]))
    lines = []
    lines.append("% Auto-generated by visualize.py -- requires \\usepackage{booktabs}")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append(f"\\caption{{Seed-fate prediction accuracy ({sampler}). "
                 "\\emph{Best acc.}\\ is the highest full accuracy over the anchor sweep; "
                 "\\emph{Anchors} is the count achieving it; \\emph{Mode} and \\emph{Halluc.}\\ "
                 "are per-class accuracies at that anchor count (any mislabel counts as wrong).}")
    lines.append(f"\\label{{tab:atlas-{sampler}}}")
    lines.append("\\begin{tabular}{cc rrrr}")
    lines.append("\\toprule")
    lines.append("$K$ & $d$ & Best acc. & Anchors & Mode acc. & Halluc. acc. \\\\")
    lines.append("\\midrule")
    prev_K = None
    for r in results:
        b = r.get("best")
        if b is None:
            continue
        K = r["K"]; d = r["d"]
        if prev_K is not None and K != prev_K:
            lines.append("\\midrule")
        prev_K = K
        best = b["full_acc"] * 100
        anc = b["n_anchors"]
        mode = b["mode_acc"] * 100
        hall = b["hall_acc"] * 100 if b["hall_acc"] == b["hall_acc"] else float("nan")
        hall_str = "--" if hall != hall else f"{hall:.1f}"
        lines.append(f"{K} & {d} & {best:.1f} & {anc:,} & {mode:.1f} & {hall_str} \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    tex = "\n".join(lines) + "\n"
    p = os.path.join(viz_dir, f"table_{sampler}.tex")
    with open(p, "w") as f:
        f.write(tex)
    return p


def plot_best_accuracy_heat(cfg, blob, viz_dir):
    """Heatmap of best full accuracy over the (d, K) grid."""
    import numpy as np
    results = blob["results"]
    Ks = sorted({r["K"] for r in results})
    ds = sorted({r["d"] for r in results})
    dk = _by_dk(results)
    A = np.full((len(Ks), len(ds)), np.nan)
    for i, K in enumerate(Ks):
        for j, d in enumerate(ds):
            r = dk.get((d, K))
            if r and r.get("best"):
                A[i, j] = r["best"]["full_acc"]
    fig, ax = plt.subplots(figsize=(1.4 * len(ds) + 2, 1.0 * len(Ks) + 2))
    im = ax.imshow(A, vmin=0, vmax=1, aspect="auto", cmap="viridis")
    ax.set_xticks(range(len(ds))); ax.set_xticklabels(ds)
    ax.set_yticks(range(len(Ks))); ax.set_yticklabels(Ks)
    ax.set_xlabel("dimension d"); ax.set_ylabel("modes K")
    ax.set_title(f"Best full accuracy ({blob.get('sampler', cfg.sampler)})")
    for i in range(len(Ks)):
        for j in range(len(ds)):
            if A[i, j] == A[i, j]:
                ax.text(j, i, f"{A[i,j]*100:.0f}", ha="center", va="center",
                        color="white" if A[i, j] < 0.6 else "black", fontsize=8)
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    fig.tight_layout()
    p = os.path.join(viz_dir, "best_accuracy_heatmap.png")
    fig.savefig(p, dpi=150, bbox_inches="tight"); plt.close(fig)
    return p


def plot_hallucination_vs_dim(cfg, blob, viz_dir):
    results = blob["results"]
    Ks = sorted({r["K"] for r in results})
    ds = sorted({r["d"] for r in results})
    dk = _by_dk(results)
    fig, ax = plt.subplots(figsize=(7, 5))
    for K in Ks:
        xs = [d for d in ds if (d, K) in dk]
        ys = [dk[(d, K)]["hall_gt"] for d in xs]
        if xs:
            ax.plot(xs, ys, "o-", label=f"K={K}")
    ax.set_xscale("log", base=2); ax.set_xticks(ds); ax.set_xticklabels(ds)
    ax.grid(alpha=.3); ax.set_xlabel("dimension d")
    ax.set_ylabel("ground-truth hallucination rate")
    ax.set_title("Hallucination rate vs dimension"); ax.legend(fontsize=8)
    fig.tight_layout()
    p = os.path.join(viz_dir, "hallucination_vs_dim.png")
    fig.savefig(p, dpi=150, bbox_inches="tight"); plt.close(fig)
    return p


def run(cfg) -> dict:
    viz_dir = os.path.join(cfg.paths.viz, cfg.sampler)
    os.makedirs(viz_dir, exist_ok=True)
    blob = _load(cfg)
    made = []
    for fn in (plot_accuracy_vs_dimension, plot_accuracy_vs_anchors,
               plot_hallucination_vs_dim, plot_best_accuracy_heat, write_latex_table):
        try:
            made.append(fn(cfg, blob, viz_dir))
        except Exception as e:  # a single bad panel shouldn't kill the rest
            print(f"[viz] {fn.__name__} failed: {e}")
    for p in made:
        print(f"[viz] wrote {p}")
    return {"figures": made}
